# Generated by Django 4.0.4 on 2023-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_alter_userprofile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
